ktor:
  deployment:
    port: 8001
    host: 0.0.0.0

  application:
    modules:
      - com.example.ApplicationKt.module
logging:
  config: classpath:logback.xml

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/test"
  username: "postgres"
  password: "123321"
  driverClassName: "org.postgresql.Driver"

  maximumPoolSize: 10
  minimumIdle: 2
  idleTimeout: 30000
  maxLifetime: 1800000
  connectionTimeout: 30000


redis:
  host: 127.0.0.1
  port: 6379
  password: null
  database: 0

  timeout: 10000
  connectTimeout: 10000

  pool:
    maxTotal: 64
    maxIdle: 10
    minIdle: 2