ktor {
  deployment {
    port = 8001
    host = "0.0.0.0"
  }

  application {
    modules = [ "com.example.ApplicationKt.module" ]
  }
}

logging {
  config = "classpath:logback.xml"
}

jwt {
  admin {
    secret = "secret-key-12345"
    issuer = "http://0.0.0"
    expiresIn = 3600
    audience = "admin"
    realm = "admin"
    # 排除不需要 JWT 校验的路由
    excludePaths = [
      "/admin/auth/login",
      "/admin/captcha/create",
    ]
  }

  app {
    secret = "secret-key-56789"
    issuer = "http://0.0.0"
    expiresIn = 3600
    audience = "app"
    realm = "app"
    # 排除不需要 JWT 校验的路由
    excludePaths = ["/app/register", "/app/public"]
  }
}

database {
  jdbcUrl = "jdbc:postgresql://localhost:5432/test"
  username = "postgres"
  password = "123321"
  schemas = ["public"]
  driverClassName = "org.postgresql.Driver"

  maximumPoolSize = 10
  minimumIdle = 2
  idleTimeout = 30000
  maxLifetime = 1800000
  connectionTimeout = 30000
}

redis {
  host = "127.0.0.1"
  port = 6379
  password = null
  database = 0

  timeout = 10000
  connectTimeout = 10000

  pool {
    maxTotal = 64
    maxIdle = 10
    minIdle = 2
  }
}

storage {
  default = "aliyun"

  aliyun {
    endpoint = ""
    accessKeyId = "111"
    accessKeySecret = "111"
    bucket = ""
    uploadPrefix = "tmp/"
  }
}

sms {
  aliyun {
    accessKeyId = "111"
    accessKeySecret = "111"
    endpoint = "dysmsapi.aliyuncs.com"
    regionId = "111"
    signName = "111"
  }
}