-- ============================================================
-- V1.0.2 初始化：Spring Batch 批处理表
-- Autogenerated: do not edit this file
-- ============================================================

-- 创建 BATCH_JOB_INSTANCE 表
CREATE TABLE "public".BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,         -- 作业实例 ID
    VERSION BIGINT,                                      -- 版本号
    JOB_NAME VARCHAR(100) NOT NULL,                      -- 作业名称
    JOB_KEY VARCHAR(32) NOT NULL,                      -- 作业唯一键
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

-- 创建 BATCH_JOB_EXECUTION 表
CREATE TABLE "public".BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,        -- 作业执行 ID
    VERSION BIGINT,                                      -- 版本号
    JOB_INSTANCE_ID BIGINT NOT NULL,                     -- 作业实例 ID
    CREATE_TIME TIMESTAMP NOT NULL,                      -- 创建时间
    START_TIME TIMESTAMP DEFAULT NULL,                   -- 开始时间
    END_TIME TIMESTAMP DEFAULT NULL,                     -- 结束时间
    STATUS VARCHAR(10),                                  -- 执行状态
    EXIT_CODE VARCHAR(2500),                             -- 退出码
    EXIT_MESSAGE VARCHAR(2500),                          -- 退出信息
    LAST_UPDATED TIMESTAMP,                              -- 最后更新时间
    CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES "public".BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

-- 创建 BATCH_JOB_EXECUTION_PARAMS 表
CREATE TABLE "public".BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,                    -- 作业执行 ID
    PARAMETER_NAME VARCHAR(100) NOT NULL,                -- 参数名称
    PARAMETER_TYPE VARCHAR(100) NOT NULL,                -- 参数类型
    PARAMETER_VALUE VARCHAR(2500),                       -- 参数值
    IDENTIFYING CHAR(1) NOT NULL,                        -- 是否标识参数
    CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES "public".BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- 创建 BATCH_STEP_EXECUTION 表
CREATE TABLE "public".BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,       -- 步骤执行 ID
    VERSION BIGINT NOT NULL,                             -- 版本号
    STEP_NAME VARCHAR(100) NOT NULL,                     -- 步骤名称
    JOB_EXECUTION_ID BIGINT NOT NULL,                    -- 作业执行 ID
    CREATE_TIME TIMESTAMP NOT NULL,                      -- 创建时间
    START_TIME TIMESTAMP DEFAULT NULL,                   -- 开始时间
    END_TIME TIMESTAMP DEFAULT NULL,                     -- 结束时间
    STATUS VARCHAR(10),                                  -- 执行状态
    COMMIT_COUNT BIGINT,                                 -- 提交次数
    READ_COUNT BIGINT,                                   -- 读取数量
    FILTER_COUNT BIGINT,                                 -- 过滤数量
    WRITE_COUNT BIGINT,                                  -- 写入数量
    READ_SKIP_COUNT BIGINT,                              -- 读取跳过数量
    WRITE_SKIP_COUNT BIGINT,                             -- 写入跳过数量
    PROCESS_SKIP_COUNT BIGINT,                           -- 处理跳过数量
    ROLLBACK_COUNT BIGINT,                               -- 回滚次数
    EXIT_CODE VARCHAR(2500),                             -- 退出码
    EXIT_MESSAGE VARCHAR(2500),                          -- 退出信息
    LAST_UPDATED TIMESTAMP,                              -- 最后更新时间
    CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES "public".BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- 创建 BATCH_STEP_EXECUTION_CONTEXT 表
CREATE TABLE "public".BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,       -- 步骤执行 ID
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,                -- 上下文摘要
    SERIALIZED_CONTEXT TEXT,                             -- 序列化上下文
    CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
        REFERENCES "public".BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
);

-- 创建 BATCH_JOB_EXECUTION_CONTEXT 表
CREATE TABLE "public".BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,        -- 作业执行 ID
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,                -- 上下文摘要
    SERIALIZED_CONTEXT TEXT,                             -- 序列化上下文
    CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES "public".BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

-- 创建序列
CREATE SEQUENCE "public".BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE "public".BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE "public".BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
